server:
  port: 8080

spring:
  application:
    name: UzRailways
  datasource:
    username: postgres
    password: 1111
    url: jdbc:postgresql://localhost:5432/uz_railways_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
